### ISSUE TITLE
【bug反馈】消息列表中的小横幅显示异常

### ISSUE THREAD

**Issue by PigeonP** [Lukoning/RevisedSecondaryWindows#1]
如图所示，无法关闭
![Clip_2024-08-14_17-56-45](https://github.com/user-attachments/assets/a1caf607-651a-46d7-a00e-70089abe06ab)
![Clip_2024-08-14_17-56-59](https://github.com/user-attachments/assets/0dc4d1b2-3769-4ebd-b08a-a6dc1a00942a)

**Comment by Lukoning** [comment]
这个横幅好像只会出现一次（我关了），甚至调试工具里都没有它的代码……
可以试着先把我的插件卸了，关掉横幅然后再装回来？

**Comment by PigeonP** [comment]
Well, 确实只会出现一遍，问题已解决。
不用卸载插件，从设置页总开关关闭后操作即可（你不会忘了你还有个插件设置页吧）
另外，既然您说了调试工具找不到对象代码，可以考虑在下一个版本多写一行提示？

**Comment by Lukoning** [comment]
阿巴巴，确实忘了。
重装网易云后这个横幅又出来了，代码也有了，下个版本改一下

**Comment by ymy139** [comment]
反正这玩意没啥用，约等于广告了，我觉得可以直接`display: none`（

**Comment by ymy139** [comment]
以及，现在这个玩意的class是`j-new-song-tip`，显然与显示内容有关连，我怀疑这个东西的class以后应该会变
当然如果佬有思路当我没说
