### ISSUE TITLE
【bug反馈】播放列表展开动画*卡顿[?]*，没有收起动画；右下角“已开始播放”气泡淡出动画消失的问题

### ISSUE THREAD

**Issue by PigeonP** [Lukoning/RevisedSecondaryWindows#2]
****有声视频，前请注意音量大小**

https://github.com/user-attachments/assets/4f94207d-e63c-4943-8c53-4c341ae3a0cf

由视频所见：
在插件关闭状态下，右下角“已开始播放”气泡有淡出动画，播放列表为闪现出入；
打开插件后，右下角“已开始播放”气泡淡出动画消失，播放列表展开动画感觉有点卡顿，且也没有收起动画。

**Comment by Lukoning** [comment]
淡出动画修了，等更新
播放列表的展开动画……确实，有时甚至还会闪现，这跟播放列表的加载机制有关
同样这个加载机制导致我**(口吐芬芳)没有办法**添加收起动画
（至少没找到办法，不然早加了，看着闪现不难受嘛）

我试看能不能解决一下展开动画的问题
