### ISSUE TITLE
[Bug] 在歌曲评论区翻页时会导致排版错乱

### ISSUE THREAD

**Issue by laoshuikaixue** [Lukoning/RevisedSecondaryWindows#3]
https://github.com/user-attachments/assets/c9a7a2f5-0265-4a0c-86e6-5217dd75686e

见视频 未使用单插件进行测试

**Comment by Lukoning** [comment]
有够奇怪的……
我排查一下

**Comment by Lukoning** [comment]
已解决
https://github.com/Lukoning/RevisedSecondaryWindows/releases/tag/v0.4.2

**Comment by laoshuikaixue** [comment]
> 已解决 https://github.com/Lukoning/RevisedSecondaryWindows/releases/tag/v0.4.2

感谢 辛苦
