### ISSUE TITLE
[BUG] 当打开私信后一段时间 窗口自动缩回 不方便打字

### ISSUE THREAD

**Issue by laoshuikaixue** [Lukoning/RevisedSecondaryWindows#4]
如题 即使焦点在输入框内时 窗口还是会自动缩回 打几个字就要重新按一下私信 不是很方便

**Comment by Lukoning** [comment]
尝试复现，发现只要鼠标左键在私信窗口外松开，窗口就会缩回

鉴于插件没有修改有关窗口消失的任何逻辑（只是添加了动画），并且这边卸载插件后问题仍然存在，应该是网易云自身的bug

方便的话可以提供一下录屏吗

**Comment by Lukoning** [comment]
如视频
https://github.com/user-attachments/assets/de147801-dc11-40ad-8829-884cf3b50b5e

**Comment by laoshuikaixue** [comment]
测试发现删除本插件还是存在这个问题 应该是其他插件的问题 不好排查暂时也不知道了

**Comment by Lukoning** [comment]
我都把BetterNCM卸了还是有这个问题🙄只能是网易云本身的问题了
